language: python
sudo: required
services:
  - docker
cache: pip
env:
  MIN_PYLINT_SCORE: 8
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev --skip-lock
  - pipenv install ./ --skip-lock
  - pipenv run nose2 -s arxiv/marxdown --with-coverage
after_success:
  - coveralls
