language: python
sudo: required
services:
  - docker
cache: pip
env:
  MIN_PYLINT_SCORE: 8
  BOTO_CONFIG: /dev/null 
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv install --dev --skip-lock
  - pipenv install ./ --skip-lock
  - pipenv run pytest --cov=arxiv/marxdown --cov=arxiv/sitemap --cov-report=term-missing arxiv/sitemap arxiv/marxdown
after_success:
  - coveralls
